In [4]:
import numpy as np
import pandas as pd

# Set seed for reproducibility
np.random.seed(42)

# Define matrix sizes
m, n, p = 3, 2, 3  # A is m x n, B is n x p

# Generate random integer matrices
A = np.random.randint(0, 10, (m, n))
B = np.random.randint(0, 10, (n, p))

# Save as CSV
pd.DataFrame(A).to_csv('A.csv', index=False, header=False)
pd.DataFrame(B).to_csv('B.csv', index=False, header=False)

# Show the matrices
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)


Matrix A:
[[6 3]
 [7 4]
 [6 9]]

Matrix B:
[[2 6 7]
 [4 3 7]]


In [5]:
def single_step_mapper(A, B):
    m, n = A.shape
    n, p = B.shape
    
    mapped = []
    
    # Emit all elements of A
    for i in range(m):
        for k in range(n):
            for j in range(p):
                mapped.append(((i, j), ('A', k, A[i][k])))

    # Emit all elements of B
    for k in range(n):
        for j in range(p):
            for i in range(m):
                mapped.append(((i, j), ('B', k, B[k][j])))

    return mapped


In [6]:
from collections import defaultdict

def single_step_reducer(mapped_data):
    grouped = defaultdict(list)
    
    # Group by key
    for key, value in mapped_data:
        grouped[key].append(value)

    # Reduce: Multiply and sum products
    result = {}
    for key, values in grouped.items():
        A_vals = {k: v for tag, k, v in values if tag == 'A'}
        B_vals = {k: v for tag, k, v in values if tag == 'B'}
        
        total = 0
        for k in A_vals:
            if k in B_vals:
                total += A_vals[k] * B_vals[k]
        result[key] = total

    return result


In [7]:
# Read the matrices back
A = pd.read_csv('A.csv', header=None).values
B = pd.read_csv('B.csv', header=None).values

# Step 1: Map
mapped = single_step_mapper(A, B)

# Step 2: Reduce
reduced = single_step_reducer(mapped)

# Format result matrix
m, p = A.shape[0], B.shape[1]
C = np.zeros((m, p), dtype=int)

for (i, j), val in reduced.items():
    C[i][j] = val

print("Resultant Matrix C (A x B):")
print(C)


Resultant Matrix C (A x B):
[[ 24  45  63]
 [ 30  54  77]
 [ 48  63 105]]


In [10]:
import pandas as pd

A = pd.read_csv("A.csv", header=None).values
B = pd.read_csv("B.csv", header=None).values


In [11]:
multi_mapped = multistep_mapper(A, B)
multi_reduced = multistep_reducer(multi_mapped)

m, p = A.shape[0], B.shape[1]
C_multi = np.zeros((m, p), dtype=int)

for (i, j), val in multi_reduced.items():
    C_multi[i][j] = val

print("Matrix C from Multi-Step MapReduce:")
print(C_multi)


Matrix C from Multi-Step MapReduce:
[[ 24  45  63]
 [ 30  54  77]
 [ 48  63 105]]


In [12]:
A = np.random.randint(1, 100, size=(100, 100))
B = np.random.randint(1, 100, size=(100, 100))


In [13]:
import time

start = time.time()
# ... run MapReduce method ...
end = time.time()
print("Time taken:", end - start)


Time taken: 7.343292236328125e-05


In [15]:
# Single-Step MapReduce functions
def mapper(A, B):
    mapped = []
    m, n = A.shape
    n2, p = B.shape
    assert n == n2, "Matrix dimensions do not align for multiplication"

    for i in range(m):
        for k in range(n):
            for j in range(p):
                mapped.append(((i, j), A[i][k] * B[k][j]))
    return mapped

def reducer(mapped):
    reduced = {}
    for key, value in mapped:
        if key not in reduced:
            reduced[key] = 0
        reduced[key] += value
    return reduced


In [16]:
import time

# Generate new matrices
A = np.random.randint(1, 100, size=(100, 100))
B = np.random.randint(1, 100, size=(100, 100))

# Time single-step
start = time.time()
single_mapped = mapper(A, B)
single_reduced = reducer(single_mapped)
C_single = np.zeros((A.shape[0], B.shape[1]), dtype=int)
for (i, j), val in single_reduced.items():
    C_single[i][j] = val
end = time.time()
print("Single-step time:", end - start)

# Time multi-step
start = time.time()
multi_mapped = multistep_mapper(A, B)
multi_reduced = multistep_reducer(multi_mapped)
C_multi = np.zeros((A.shape[0], B.shape[1]), dtype=int)
for (i, j), val in multi_reduced.items():
    C_multi[i][j] = val
end = time.time()
print("Multi-step time:", end - start)


Single-step time: 1.0080547332763672
Multi-step time: 0.971498966217041


In [17]:
import time

# Generate new matrices
A = np.random.randint(1, 10, size=(10, 10))
B = np.random.randint(1, 10, size=(10, 10))

# Time single-step
start = time.time()
single_mapped = mapper(A, B)
single_reduced = reducer(single_mapped)
C_single = np.zeros((A.shape[0], B.shape[1]), dtype=int)
for (i, j), val in single_reduced.items():
    C_single[i][j] = val
end = time.time()
print("Single-step time:", end - start)

# Time multi-step
start = time.time()
multi_mapped = multistep_mapper(A, B)
multi_reduced = multistep_reducer(multi_mapped)
C_multi = np.zeros((A.shape[0], B.shape[1]), dtype=int)
for (i, j), val in multi_reduced.items():
    C_multi[i][j] = val
end = time.time()
print("Multi-step time:", end - start)


Single-step time: 0.07583284378051758
Multi-step time: 0.07576394081115723


In [19]:
import time

# Generate new matrices
A = np.random.randint(1, 50, size=(50, 50))
B = np.random.randint(1, 50, size=(50, 50))

# Time single-step
start = time.time()
single_mapped = mapper(A, B)
single_reduced = reducer(single_mapped)
C_single = np.zeros((A.shape[0], B.shape[1]), dtype=int)
for (i, j), val in single_reduced.items():
    C_single[i][j] = val
end = time.time()
print("Single-step time:", end - start)

# Time multi-step
start = time.time()
multi_mapped = multistep_mapper(A, B)
multi_reduced = multistep_reducer(multi_mapped)
C_multi = np.zeros((A.shape[0], B.shape[1]), dtype=int)
for (i, j), val in multi_reduced.items():
    C_multi[i][j] = val
end = time.time()
print("Multi-step time:", end - start)


Single-step time: 0.14161348342895508
Multi-step time: 0.11689400672912598


In [21]:
import time

# Generate new matrices
A = np.random.randint(1, 200, size=(200, 200))
B = np.random.randint(1, 200, size=(200, 200))

# Time single-step
start = time.time()
single_mapped = mapper(A, B)
single_reduced = reducer(single_mapped)
C_single = np.zeros((A.shape[0], B.shape[1]), dtype=int)
for (i, j), val in single_reduced.items():
    C_single[i][j] = val
end = time.time()
print("Single-step time:", end - start)

# Time multi-step
start = time.time()
multi_mapped = multistep_mapper(A, B)
multi_reduced = multistep_reducer(multi_mapped)
C_multi = np.zeros((A.shape[0], B.shape[1]), dtype=int)
for (i, j), val in multi_reduced.items():
    C_multi[i][j] = val
end = time.time()
print("Multi-step time:", end - start)


Single-step time: 97.12206721305847
Multi-step time: 11.947098970413208
